import { IContact } from './contact.types';
import { IAttachment } from './attachment.types';
import { IComment } from './comment.types';
import { IProfile } from './profile.types';
import { IUserDetails } from './user.types';
import { ITag } from './tag.types';
import { ITeam } from './team.types';

export interface ILead {
    id: string;
    title: string;
    first_name: string;
    last_name: string;
    phone: string;
    email: string;
    status: string;
    status_display: string | null;
    source: string;
    source_display: string | null;
    address_line: string;
    contacts: IContact[];
    street: string;
    city: string;
    state: string;
    postcode: string;
    country: string;
    website: string;
    description: string;
    lead_attachment: IAttachment[];
    lead_comments: IComment[];
    assigned_to: IProfile[];
    account_name: string;
    opportunity_amount: string;
    created_by: IUserDetails;
    created_at: string;
    is_active: boolean;
    enquiry_type: string;
    tags: ITag[];
    created_from_site: boolean;
    teams: ITeam[];
    industry: string;
    industry_display: string | null;
    company: string;
    organization: string;
    probability: number;
    close_date: string | null;
    salutation: string;
    salutation_display: string | null;
    department: string;
    department_display: string | null;
    preferred_language: string;
    preferred_language_display: string | null;
    rating: string;
    rating_display: string | null;
    budget_range: string;
    budget_range_display: string | null;
    decision_timeframe: string;
    decision_timeframe_display: string | null;
    do_not_call: boolean;
    is_converted: boolean;
}
